export type ErrorCode =
  | 'VALIDATION_ERROR'
  | 'UNAUTHENTICATED'
  | 'FORBIDDEN'
  | 'NOT_FOUND'
  | 'CONFLICT'
  | 'RATE_LIMITED'
  | 'OTP_INVALID'
  | 'OTP_EXPIRED'
  | 'OTP_LOCKED'
  | 'PROVIDER_MISMATCH'
  | 'CONSENT_REQUIRED'
  | 'TERMS_REQUIRED'
  | 'LOCATION_CONSENT_REQUIRED'
  | 'PROVIDER_NOT_VERIFIED'
  | 'NOT_ON_DUTY'
  | 'ALREADY_ASSIGNED'
  | 'OFFER_EXPIRED'
  | 'PRESCRIPTION_REQUIRED'
  | 'PRESCRIPTION_LOCKED'
  | 'TRANSCRIPTION_PENDING'
  | 'QUOTE_INVALID'
  | 'QUOTE_EXPIRED'
  | 'INVALID_TRANSITION'
  | 'VISIT_CODE_INVALID'
  | 'VISIT_CODE_LOCKED'
  | 'SUPERVISOR_NOT_JOINED'
  | 'IDEMPOTENCY_KEY_REQUIRED'
  | 'IDEMPOTENCY_KEY_REUSED'
  | 'IDEMPOTENCY_IN_PROGRESS'
  | 'NOT_SERVICEABLE'
  | 'PAYMENT_FAILED'
  | 'INTERNAL';

const STATUS: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400,
  UNAUTHENTICATED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  RATE_LIMITED: 429,
  OTP_INVALID: 400,
  OTP_EXPIRED: 400,
  OTP_LOCKED: 429,
  PROVIDER_MISMATCH: 403,
  CONSENT_REQUIRED: 422,
  TERMS_REQUIRED: 409,
  LOCATION_CONSENT_REQUIRED: 409,
  PROVIDER_NOT_VERIFIED: 403,
  NOT_ON_DUTY: 409,
  ALREADY_ASSIGNED: 409,
  OFFER_EXPIRED: 409,
  PRESCRIPTION_REQUIRED: 422,
  PRESCRIPTION_LOCKED: 409,
  TRANSCRIPTION_PENDING: 409,
  QUOTE_INVALID: 422,
  QUOTE_EXPIRED: 422,
  INVALID_TRANSITION: 409,
  VISIT_CODE_INVALID: 422,
  VISIT_CODE_LOCKED: 423,
  SUPERVISOR_NOT_JOINED: 409,
  IDEMPOTENCY_KEY_REQUIRED: 400,
  IDEMPOTENCY_KEY_REUSED: 422,
  IDEMPOTENCY_IN_PROGRESS: 409,
  NOT_SERVICEABLE: 422,
  PAYMENT_FAILED: 402,
  INTERNAL: 500,
};

export class AppError extends Error {
  readonly statusCode: number;
  constructor(
    readonly code: ErrorCode,
    message?: string,
    readonly details?: unknown,
  ) {
    super(message ?? code);
    this.statusCode = STATUS[code];
  }
}

export const notFound = (what = 'Resource') => new AppError('NOT_FOUND', `${what} not found`);
export const forbidden = (msg = 'Not allowed') => new AppError('FORBIDDEN', msg);
